Daniel/main content
DanielGovrin/ecommerce pull request #2
Opened 2023-12-04 08:36 UTC by DanielGovrin

2023-12-04 09:07 UTC, TheAlmightyCrumb requested changes

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on public/HatImages/adidas_cap_image.jpg
Instead of including all your assets in `public`, include them in `src` and be precise with naming conventions.
I suggest `src/assets/hat-images/[image_file]`.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/App.tsx
> +import styles from './app.module.css'
Sort imports.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/AddToCart.tsx
> +   }
What is this function and why do you need it?

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/Data.tsx
> +      Price: '$39.99',
Stick to camelcase naming in object keys. `mainTitle`, `secondaryTitle` and so on.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/addtocart.module.css
> +   border-radius: 10px;
Duplicate, can remove the first one.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/card.tsx
> +            <h3 className={styles.SecondaryTitle}>{SecondaryTitle}</h3>
These classes don't exist in the stylesheet they're imported from.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/data.tsx
Do you have two data files? I'm not sure what happens here 😅

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/datatypes.ts
> +   Price: string;
Naming uniformity, stick with camelcase here.

2023-12-04 09:07 UTC, TheAlmightyCrumb commented on src/Components/datatypes.ts
> +   Price: string;
Naming uniformity, stick with camelcase here.

2023-12-04 10:18 UTC, DanielGovrin commented on src/Components/AddToCart.tsx
> +   }
This function is for future implementation of the button, later on it will implement the actual adding the product to the client cart.

2023-12-04 10:19 UTC, DanielGovrin commented on src/Components/data.tsx
One is for the data itself and one is for the datatypes

2023-12-07 09:56 UTC, TheAlmightyCrumb approved these changes

2023-12-07 09:56 UTC, TheAlmightyCrumb commented on src/App.tsx
> +import Sidebar from './components/sidebar';
Uniformity in file names and directories. I'd avoid caps and go with lowercase.

2023-12-10 08:23 UTC, merged